📅 DAY 4 — Pandas GroupBy & Aggregation (CORE ANALYST SKILL)

In [10]:
import pandas as pd
from google.colab import files

# 1. Create the data dictionary
data = {
    'OrderID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    'Date': [
        '2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02',
        '2024-01-03', '2024-01-03', '2024-01-04', '2024-01-04'
    ],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['Phone', 'Laptop', 'Chair', 'Table', 'Phone', 'Chair', 'Laptop', 'Phone'],
    'Category': ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Electronics', 'Furniture', 'Electronics', 'Electronics'],
    'Sales': [15000, 55000, 7000, 12000, 15000, 7000, 55000, 15000],
    'Quantity': [2, 1, 3, 2, 1, 2, 1, 2]
}

# 2. Create the DataFrame
df = pd.DataFrame(data)

# Optional: Convert 'Date' column to proper datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Display the DataFrame to verify
print("Preview of the created table:")
display(df)

# 3. Save to CSV (index=False removes the row numbers)
filename = 'sales_data.csv'
df.to_csv(filename, index=False)

# 4. Download the file to your local machine
files.download(filename)

Preview of the created table:


OrderID       Date Region Product     Category  Sales  Quantity
0     1001 2024-01-01  North   Phone  Electronics  15000         2
1     1002 2024-01-01  South  Laptop  Electronics  55000         1
2     1003 2024-01-02   East   Chair    Furniture   7000         3
3     1004 2024-01-02   West   Table    Furniture  12000         2
4     1005 2024-01-03  North   Phone  Electronics  15000         1
5     1006 2024-01-03  South   Chair    Furniture   7000         2
6     1007 2024-01-04   East  Laptop  Electronics  55000         1
7     1008 2024-01-04   West   Phone  Electronics  15000         2

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

🧠 SECTION 1: WHAT GROUPBY REALLY MEANS

Write this in markdown notes:

GroupBy splits data into groups based on a column, applies a function to each group, and combines the results.

Split → Apply → Combine

In [11]:
# 🧪 SECTION 2: BASIC GROUPBY (NON-NEGOTIABLE)
import pandas as pd

df = pd.read_csv("sales_data.csv")
df

# Total sales by Region
df.groupby("Region")["Sales"].sum()

Region
East     62000
North    30000
South    62000
West     27000
Name: Sales, dtype: int64

In [12]:

# 🧪 SECTION 3: MULTIPLE AGGREGATIONS
df.groupby("Category").agg(
    Total_Sales=("Sales", "sum"),
    Avg_Sales=("Sales", "mean"),
    Total_Quantity=("Quantity", "sum")
)


Total_Sales     Avg_Sales  Total_Quantity
Category                                              
Electronics       155000  31000.000000               7
Furniture          26000   8666.666667               7

In [13]:
# 🧪 SECTION 4: GROUP BY MULTIPLE COLUMNS
df.groupby(["Region", "Category"])["Sales"].sum()


# Then:

df.groupby(["Region", "Category"])["Sales"].sum().reset_index()

Region     Category  Sales
0   East  Electronics  55000
1   East    Furniture   7000
2  North  Electronics  30000
3  South  Electronics  55000
4  South    Furniture   7000
5   West  Electronics  15000
6   West    Furniture  12000

In [14]:
# 🧪 SECTION 5: SORTING GROUPBY RESULTS
region_sales = df.groupby("Region")["Sales"].sum().reset_index()
region_sales.sort_values(by="Sales", ascending=False)

Region  Sales
0   East  62000
2  South  62000
1  North  30000
3   West  27000

🧠 SECTION 6: BUSINESS QUESTIONS

Answer in markdown, not code:

Which region has the highest total sales?

Which product category sells more overall?

Which region–category combination performs best?

Is Electronics outperforming Furniture?

## Identify Top Region by Sales

### Subtask:
Analyze the total sales by region to identify which region has the highest total sales, using the existing `region_sales` data.


**Reasoning**:
The subtask requires displaying the `region_sales` DataFrame to inspect its contents and then identifying the region with the highest sales. Displaying the dataframe is the first step in this process.



In [15]:
print("Displaying the region_sales DataFrame sorted by sales:")
display(region_sales)

Displaying the region_sales DataFrame sorted by sales:


Region  Sales
0   East  62000
1  North  30000
2  South  62000
3   West  27000

**Reasoning**:
The `NameError` indicates that `region_sales` was not defined when the previous cell was executed. To fix this, I need to recalculate `region_sales` by grouping the `df` DataFrame by 'Region' and summing the 'Sales', then sort it in ascending order as specified in the instructions, and finally display the DataFrame and extract the highest sales region.



In [16]:
import pandas as pd

# Ensure df is defined - assuming 'sales_data.csv' exists from previous steps
# If df is not defined in the current session, load it:
try:
    df.head()
except NameError:
    df = pd.read_csv('sales_data.csv')

# Recalculate region_sales and sort it in ascending order for highest to be at the last row
region_sales = df.groupby("Region")["Sales"].sum().reset_index()
region_sales = region_sales.sort_values(by="Sales", ascending=True)

print("Displaying the region_sales DataFrame sorted by sales:")
display(region_sales)

# Identify the region with the highest total sales (last row after ascending sort)
highest_sales_region_row = region_sales.iloc[-1]
highest_sales_region = highest_sales_region_row['Region']
highest_sales_value = highest_sales_region_row['Sales']

print(f"\nThe region with the highest total sales is '{highest_sales_region}' with sales of {highest_sales_value}.")

Displaying the region_sales DataFrame sorted by sales:


Region  Sales
3   West  27000
1  North  30000
0   East  62000
2  South  62000


The region with the highest total sales is 'South' with sales of 62000.


**Reasoning**:
The previous error `FileNotFoundError: [Errno 2] No such file or directory: 'sales_data.csv'` indicates that the CSV file could not be found, likely because the environment was reset or the file was not persisted. To ensure the `df` DataFrame is always available, I will re-create it directly from the original data dictionary within this cell, then proceed with calculating and displaying `region_sales` and identifying the highest sales region.



In [4]:
import pandas as pd

# Re-create the data dictionary
data = {
    'OrderID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    'Date': [
        '2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02',
        '2024-01-03', '2024-01-03', '2024-01-04', '2024-01-04'
    ],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['Phone', 'Laptop', 'Chair', 'Table', 'Phone', 'Chair', 'Laptop', 'Phone'],
    'Category': ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Electronics', 'Furniture', 'Electronics', 'Electronics'],
    'Sales': [15000, 55000, 7000, 12000, 15000, 7000, 55000, 15000],
    'Quantity': [2, 1, 3, 2, 1, 2, 1, 2]
}

# Re-create the DataFrame
df = pd.DataFrame(data)

# Convert 'Date' column to proper datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Recalculate region_sales and sort it in ascending order for highest to be at the last row
region_sales = df.groupby("Region")["Sales"].sum().reset_index()
region_sales = region_sales.sort_values(by="Sales", ascending=True)

print("Displaying the region_sales DataFrame sorted by sales:")
display(region_sales)

# Identify the region with the highest total sales (last row after ascending sort)
highest_sales_region_row = region_sales.iloc[-1]
highest_sales_region = highest_sales_region_row['Region']
highest_sales_value = highest_sales_region_row['Sales']

print(f"\nThe region with the highest total sales is '{highest_sales_region}' with sales of {highest_sales_value}.")

Displaying the region_sales DataFrame sorted by sales:


Region  Sales
3   West  27000
1  North  30000
0   East  62000
2  South  62000


The region with the highest total sales is 'South' with sales of 62000.


## Identify Top Product Category and Compare Sales

### Subtask:
Calculate the total sales for each product category to determine which category sells the most overall and to compare the sales performance of 'Electronics' against 'Furniture'.


**Reasoning**:
The subtask requires calculating total sales per product category, identifying the top-selling category, and comparing sales between 'Electronics' and 'Furniture'. This involves grouping the DataFrame, aggregating sales, and then extracting specific values for comparison.



In [5]:
import pandas as pd

# Ensure df is defined - recreate if necessary
try:
    df.head()
except NameError:
    # Re-create the data dictionary
    data = {
        'OrderID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
        'Date': [
            '2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02',
            '2024-01-03', '2024-01-03', '2024-01-04', '2024-01-04'
        ],
        'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
        'Product': ['Phone', 'Laptop', 'Chair', 'Table', 'Phone', 'Chair', 'Laptop', 'Phone'],
        'Category': ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Electronics', 'Furniture', 'Electronics', 'Electronics'],
        'Sales': [15000, 55000, 7000, 12000, 15000, 7000, 55000, 15000],
        'Quantity': [2, 1, 3, 2, 1, 2, 1, 2]
    }
    # Re-create the DataFrame
    df = pd.DataFrame(data)
    df['Date'] = pd.to_datetime(df['Date'])

# Group by 'Category' and sum 'Sales', then reset index
category_sales = df.groupby('Category')['Sales'].sum().reset_index()

# Identify the product category with the highest total sales
top_category_row = category_sales.sort_values(by='Sales', ascending=False).iloc[0]
top_category = top_category_row['Category']
top_category_sales = top_category_row['Sales']

# Extract sales for 'Electronics' and 'Furniture'
electronics_sales = category_sales[category_sales['Category'] == 'Electronics']['Sales'].iloc[0]
furniture_sales = category_sales[category_sales['Category'] == 'Furniture']['Sales'].iloc[0]

print(f"Total Sales by Category:\n{category_sales}\n")
print(f"The product category with the highest total sales is '{top_category}' with sales of {top_category_sales}.")
print(f"Total sales for 'Electronics': {electronics_sales}")
print(f"Total sales for 'Furniture': {furniture_sales}")

Total Sales by Category:
      Category   Sales
0  Electronics  155000
1    Furniture   26000

The product category with the highest total sales is 'Electronics' with sales of 155000.
Total sales for 'Electronics': 155000
Total sales for 'Furniture': 26000


## Identify Best Region-Category Combination

### Subtask:
Examine the total sales for each region-category combination to find the one with the highest sales, using the existing grouped data.


## Identify Best Region-Category Combination

### Subtask:
Examine the total sales for each region-category combination to find the one with the highest sales, using the existing grouped data.

#### Instructions
1. Group the DataFrame `df` by both 'Region' and 'Category'.
2. Calculate the sum of 'Sales' for each group.
3. Reset the index of the resulting DataFrame to turn the grouped keys into columns.
4. Sort this new DataFrame by 'Sales' in descending order to easily identify the best combination.
5. Extract the row corresponding to the highest sales to identify the best region-category combination and its sales value.

**Reasoning**:
The subtask instructions have been outlined, now I will write the Python code to perform the grouping, aggregation, sorting, and extraction to identify the best region-category combination.



In [6]:
import pandas as pd

# Ensure df is defined - recreate if necessary
try:
    df.head()
except NameError:
    # Re-create the data dictionary
    data = {
        'OrderID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
        'Date': [
            '2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02',
            '2024-01-03', '2024-01-03', '2024-01-04', '2024-01-04'
        ],
        'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
        'Product': ['Phone', 'Laptop', 'Chair', 'Table', 'Phone', 'Chair', 'Laptop', 'Phone'],
        'Category': ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Electronics', 'Furniture', 'Electronics', 'Electronics'],
        'Sales': [15000, 55000, 7000, 12000, 15000, 7000, 55000, 15000],
        'Quantity': [2, 1, 3, 2, 1, 2, 1, 2]
    }
    # Re-create the DataFrame
    df = pd.DataFrame(data)
    df['Date'] = pd.to_datetime(df['Date'])

# Group by 'Region' and 'Category' and sum 'Sales', then reset index
region_category_sales = df.groupby(['Region', 'Category'])['Sales'].sum().reset_index()

# Sort in descending order to find the best combination
best_combination = region_category_sales.sort_values(by='Sales', ascending=False).iloc[0]

print("Total Sales by Region and Category:\n")
display(region_category_sales)
print(f"\nThe best performing region-category combination is '{best_combination['Region']} - {best_combination['Category']}' with sales of {best_combination['Sales']}.")

Total Sales by Region and Category:



Region     Category  Sales
0   East  Electronics  55000
1   East    Furniture   7000
2  North  Electronics  30000
3  South  Electronics  55000
4  South    Furniture   7000
5   West  Electronics  15000
6   West    Furniture  12000


The best performing region-category combination is 'East - Electronics' with sales of 55000.


## Present Business Answers

### Subtask:
Compile the findings from the analysis into markdown format, providing clear answers to all the business questions asked.


**Reasoning**:
I have all the necessary variables from previous steps. I will use a code block to construct a markdown string using these variables to answer the business questions and then print this markdown string.



In [7]:
markdown_answer = f"""### Business Questions Answered:

*   **Which region has the highest total sales?**
    The region with the highest total sales is **{highest_sales_region}** with sales of **${highest_sales_value:,.2f}**.

*   **Which product category sells more overall?**
    The product category that sells more overall is **{top_category}** with total sales of **${top_category_sales:,.2f}**.

*   **Which region–category combination performs best?**
    The best performing region-category combination is **{best_combination['Region']} - {best_combination['Category']}** with sales of **${best_combination['Sales']:.2f}**.

*   **Is 'Electronics' outperforming 'Furniture'?**
    Yes, 'Electronics' is significantly outperforming 'Furniture'. 'Electronics' had total sales of **${electronics_sales:,.2f}** while 'Furniture' had total sales of **${furniture_sales:,.2f}**.
"""

print(markdown_answer)

### Business Questions Answered:

*   **Which region has the highest total sales?**
    The region with the highest total sales is **South** with sales of **$62,000.00**.

*   **Which product category sells more overall?**
    The product category that sells more overall is **Electronics** with total sales of **$155,000.00**.

*   **Which region–category combination performs best?**
    The best performing region-category combination is **East - Electronics** with sales of **$55000.00**.

*   **Is 'Electronics' outperforming 'Furniture'?**
    Yes, 'Electronics' is significantly outperforming 'Furniture'. 'Electronics' had total sales of **$155,000.00** while 'Furniture' had total sales of **$26,000.00**.



## Summary:

### Q&A

*   **Which region has the highest total sales?**
    The South region has the highest total sales with \$62,000.00.

*   **Which product category sells more overall?**
    The 'Electronics' category sells more overall with total sales of \$155,000.00.

*   **Which region–category combination performs best?**
    The 'East - Electronics' combination performs best with sales of \$55,000.00.

*   **Is 'Electronics' outperforming 'Furniture'?**
    Yes, 'Electronics' is significantly outperforming 'Furniture', with sales of \$155,000.00 compared to 'Furniture's' \$26,000.00.

### Data Analysis Key Findings

*   The **South** region recorded the highest total sales, reaching **\$62,000.00**. The East region also had \$62,000.00 in sales, indicating a tie for the top spot.
*   **'Electronics'** is the top-performing product category overall, generating total sales of **\$155,000.00**.
*   The most successful region-category combination is **'East - Electronics'**, with total sales of **\$55,000.00**.
*   **'Electronics'** significantly outperforms **'Furniture'**, with 'Electronics' sales being **\$155,000.00** compared to 'Furniture's' **\$26,000.00**.

### Insights or Next Steps

*   Investigate the specific factors contributing to the high sales in the 'South' region and for 'Electronics' products to replicate success in other areas or categories.
*   Analyze the product mix and marketing strategies within the 'Furniture' category to identify potential improvements, given its significantly lower sales compared to 'Electronics'.
